name: Run Laravel Tests

on:
  pull_request:
    branches: [ main ]
  # push:
  #   branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: jooohny
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, mysql
        coverage: none
    
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Create .env file directly
      run: |
        cat > .env << 'EOL'
        APP_NAME=Laravel
        APP_ENV=testing
        APP_KEY=
        APP_DEBUG=true
        APP_URL=http://localhost

        LOG_CHANNEL=stack
        LOG_LEVEL=debug

        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_DATABASE=app
        DB_USERNAME=root
        DB_PASSWORD=jooohny
        EOL
    
    - name: Generate Key
      run: php artisan key:generate
    
    - name: Display .env for debugging
      run: cat .env
    
    - name: Run Migrations
      run: php artisan migrate
    
    - name: Run Tests
      run: php artisan test